"""Initial schema

Revision ID: 19452b43c54d
Revises: 
Create Date: 2026-05-18 20:15:06.869251
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19452b43c54d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question_paper_key', sa.Text(), nullable=True),
    sa.Column('baseline_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('gemini_api_key', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grading_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('graded_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grading_runs_task_id', 'grading_runs', ['task_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_decomposition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('idx_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.create_index('idx_submissions_task_id', 'submissions', ['task_id'], unique=False)
    op.create_table('task_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('rubric_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grading_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_rubrics_task_version', 'task_rubrics', ['task_id', 'version'], unique=True)
    op.create_table('drift_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('current_run_id', sa.UUID(), nullable=False),
    sa.Column('baseline_run_id', sa.UUID(), nullable=False),
    sa.Column('kl_divergence', sa.Float(), nullable=False),
    sa.Column('mean_shift', sa.Float(), nullable=False),
    sa.Column('entropy_current', sa.Float(), nullable=False),
    sa.Column('entropy_baseline', sa.Float(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['current_run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drift_reports_task_id', 'drift_reports', ['task_id'], unique=False)
    op.create_table('grade_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('grading_run_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('max_grade', sa.Integer(), nullable=False),
    sa.Column('grade_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('step_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('llm_call_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('component_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grading_run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grade_results_review_status', 'grade_results', ['review_status'], unique=False)
    op.create_index('idx_grade_results_run_id', 'grade_results', ['grading_run_id'], unique=False)
    op.create_index('idx_grade_results_submission_id', 'grade_results', ['submission_id'], unique=False)
    op.create_table('grading_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grading_alerts_resolved', 'grading_alerts', ['resolved'], unique=False)
    op.create_index('idx_grading_alerts_task_id', 'grading_alerts', ['task_id'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('grading_run_id', sa.UUID(), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grading_run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_calls_run_id', 'llm_call_logs', ['grading_run_id'], unique=False)
    op.create_index('idx_llm_calls_submission_id', 'llm_call_logs', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_llm_calls_submission_id', table_name='llm_call_logs')
    op.drop_index('idx_llm_calls_run_id', table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index('idx_grading_alerts_task_id', table_name='grading_alerts')
    op.drop_index('idx_grading_alerts_resolved', table_name='grading_alerts')
    op.drop_table('grading_alerts')
    op.drop_index('idx_grade_results_submission_id', table_name='grade_results')
    op.drop_index('idx_grade_results_run_id', table_name='grade_results')
    op.drop_index('idx_grade_results_review_status', table_name='grade_results')
    op.drop_table('grade_results')
    op.drop_index('idx_drift_reports_task_id', table_name='drift_reports')
    op.drop_table('drift_reports')
    op.drop_index('idx_task_rubrics_task_version', table_name='task_rubrics')
    op.drop_table('task_rubrics')
    op.drop_index('idx_submissions_task_id', table_name='submissions')
    op.drop_index('idx_submissions_student_id', table_name='submissions')
    op.drop_index('idx_submissions_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('idx_grading_runs_task_id', table_name='grading_runs')
    op.drop_table('grading_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
