"""Add Phase 3 organizational models

Revision ID: 9b88d3fc71e7
Revises: 19452b43c54d
Create Date: 2026-05-21 07:38:56.987276
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b88d3fc71e7'
down_revision: Union[str, None] = '19452b43c54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_section_id'), 'students', ['section_id'], unique=False)
    op.add_column('grading_runs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'grading_runs', 'users', ['created_by'], ['id'])
    op.execute("UPDATE submissions SET student_id = NULL")
    op.alter_column('submissions', 'student_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               postgresql_using='student_id::uuid',
               nullable=True)
    op.drop_index('idx_submissions_student_id', table_name='submissions')
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_foreign_key(None, 'submissions', 'students', ['student_id'], ['id'])
    op.add_column('users', sa.Column('school_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_column('users', 'school_id')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.create_index('idx_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.alter_column('submissions', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'grading_runs', type_='foreignkey')
    op.drop_column('grading_runs', 'created_by')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('schools')
    # ### end Alembic commands ###
