"""
Observability schemas — drift reports and grading alerts.
"""
from pydantic import BaseModel


class DriftReportResponse(BaseModel):
    """Drift analysis report comparing a run to its baseline."""
    id: str
    task_id: str
    current_run_id: str
    baseline_run_id: str
    kl_divergence: float
    mean_shift: float
    entropy_current: float
    entropy_baseline: float
    drift_detected: bool
    severity: str  # LOW | MEDIUM | HIGH
    details: dict | None = None
    created_at: str

    model_config = {"from_attributes": True}


class GradingAlertResponse(BaseModel):
    """System alert generated by the observability layer."""
    id: str
    run_id: str | None
    task_id: str | None
    alert_type: str  # DRIFT | LATENCY | FAILURE_RATE | UNCERTAINTY
    severity: str  # LOW | MEDIUM | HIGH
    message: str
    metadata_json: dict | None = None
    resolved: bool
    created_at: str

    model_config = {"from_attributes": True}


class SetBaselineRequest(BaseModel):
    """Request to set a grading run as the drift baseline."""
    run_id: str
